const profileItems = ['Profile', 'All User', 'Download Invoice', 'Logout']

function AppHeader({ sidebarCollapsed, setSidebarCollapsed, setShowEway, onOpenEway, showProfileMenu, setShowProfileMenu, showCompanyMenu, setShowCompanyMenu, onProfileClick, onAllUsersClick, onMobileVersionClick, selectedCompany, companyOptions, onAddCompany, onSelectCompany, onCompanyClick, onLogout }) {
  return <>
    <header className="app-header relative z-20 flex h-auto flex-wrap items-center border-b border-slate-200 bg-white md:h-[60px] md:flex-nowrap">
      <button type="button" aria-label="Menu" aria-expanded={!sidebarCollapsed} onClick={() => setSidebarCollapsed((current) => !current)} className="header-menu flex h-[60px] w-[58px] shrink-0 flex-col items-center justify-center gap-1 border-0 border-r border-slate-200 bg-white"><span className="h-0.5 w-4 bg-slate-800" /><span className="h-0.5 w-4 bg-slate-800" /><span className="h-0.5 w-4 bg-slate-800" /></button>
      <div className="relative flex h-[60px] min-w-[160px] flex-1 items-center border-r border-slate-200 px-3 md:w-[clamp(180px,26vw,355px)] md:min-w-[180px] md:flex-none md:px-4" role="button" tabIndex={0} aria-expanded={showCompanyMenu} onClick={() => { setShowCompanyMenu((current) => !current); setShowProfileMenu(false) }}>
        <div className="min-w-0"><strong className="block truncate text-[13px] font-semibold">{selectedCompany?.name || 'Paytel Financial Services P...'}</strong><span className="block text-[11px] text-slate-500">{selectedCompany?.meta || ''}</span></div><span className="ml-2 text-xs">⌄</span>
        {showCompanyMenu && <div className="absolute left-2 top-[60px] z-30 w-80 rounded border border-slate-200 bg-white p-3 text-xs shadow-lg" onClick={(event) => event.stopPropagation()}><b className="mb-3 block text-slate-500">My Companies</b>{companyOptions?.map((company) => <button type="button" key={company.id || company.name} onClick={() => onCompanyClick?.(company) || onSelectCompany?.(company)} className="flex w-full items-start justify-between border-b border-slate-100 pb-3 text-left last:border-b-0 last:pb-0">
          <span><strong className="block">{company.name}</strong><small className="text-slate-500">{company.meta}</small></span>
        </button>)}</div>}
      </div>
      <label className="header-search mx-auto my-2 flex h-9 w-full max-w-[320px] items-center rounded-lg border border-slate-300 px-3 text-slate-400 md:my-0 md:w-[clamp(180px,28vw,320px)]"><span className="mr-2 text-lg">⌕</span><input type="text" placeholder="Search vouchers, ledgers, items" className="w-full bg-transparent text-[11px] text-slate-800 outline-none placeholder:text-slate-400" /></label>
      <div className="ml-0 flex h-[60px] w-full shrink-0 items-stretch justify-end md:ml-3 md:w-auto"><button type="button" onClick={() => (onOpenEway ? onOpenEway() : setShowEway(true))} className="flex w-[82px] items-center justify-center gap-2 border-0 border-r border-slate-200 bg-white text-[11px]"><span className="grid h-[18px] w-[18px] place-items-center rounded-full border border-red-400 text-red-500">!</span><span className="text-left leading-[13px]">Link<br />eInvoice</span></button><button type="button" onClick={onMobileVersionClick ?? (() => window.open('/mobile-version', '_blank', 'noopener,noreferrer'))} className="flex w-[106px] items-center justify-center gap-2 border-0 border-r border-slate-200 bg-white text-[11px]"><span className="text-xl">▯</span><span className="text-left leading-[13px]">Mobile<br />Version</span></button><button type="button" onClick={onAllUsersClick} className="flex h-[60px] w-[86px] items-center justify-center border-0 border-r border-slate-200 bg-white text-[11px] font-semibold text-slate-700 hover:bg-slate-50">All<br />Users</button><div className="relative"><button type="button" aria-label="Open profile menu" aria-expanded={showProfileMenu} onClick={() => setShowProfileMenu((current) => !current)} className="flex h-[60px] min-w-[75px] items-center justify-center gap-2 border-0 bg-white px-3 text-lg"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-sm">♙</span><span className="text-xs">⌄</span></button>{showProfileMenu && <div className="absolute right-2 top-[60px] z-30 w-44 rounded border border-slate-200 bg-white p-1 shadow-lg" role="menu">{profileItems.map((label) => <button type="button" role="menuitem" key={label} onClick={() => { setShowProfileMenu(false); if (label === 'Profile') onProfileClick?.(); if (label === 'All User') onAllUsersClick?.(); if (label === 'Download Invoice') { window.history.pushState({}, '', '/download-invoice'); window.dispatchEvent(new PopStateEvent('popstate')); } if (label === 'Logout') onLogout?.(); }} className="block w-full rounded px-3 py-2 text-left text-xs hover:bg-slate-100">{label}</button>)}</div>}</div></div>
    </header>
    {showCompanyMenu && <button className="fixed inset-0 z-10 cursor-default bg-transparent" type="button" aria-label="Close company menu" onClick={() => setShowCompanyMenu(false)} />}
  </>
}

export default AppHeader
