const profileItems = ['Profile', 'All User', 'Download Invoice', 'Logout']

function AppHeader({ sidebarCollapsed, setSidebarCollapsed, setShowEway, showProfileMenu, setShowProfileMenu, showCompanyMenu, setShowCompanyMenu }) {
  return <>
    <header className="app-header relative z-20 flex h-[60px] items-center border-b border-slate-200 bg-white">
      <button type="button" aria-label="Menu" aria-expanded={!sidebarCollapsed} onClick={() => setSidebarCollapsed((current) => !current)} className="header-menu flex h-[60px] w-[58px] shrink-0 flex-col items-center justify-center gap-1 border-0 border-r border-slate-200 bg-white"><span className="h-0.5 w-4 bg-slate-800" /><span className="h-0.5 w-4 bg-slate-800" /><span className="h-0.5 w-4 bg-slate-800" /></button>
      <div className="relative flex h-[60px] w-[clamp(180px,26vw,355px)] shrink-0 items-center border-r border-slate-200 px-4" role="button" tabIndex={0} aria-expanded={showCompanyMenu} onClick={() => { setShowCompanyMenu((current) => !current); setShowProfileMenu(false) }}>
        <div className="min-w-0"><strong className="block truncate text-[13px] font-semibold">Paytel Financial Services P...</strong><span className="block text-[11px] text-slate-500">Synced a day ago</span></div><span className="ml-2 text-xs">⌄</span>
        {showCompanyMenu && <div className="absolute left-2 top-[60px] z-30 w-80 rounded border border-slate-200 bg-white p-3 text-xs shadow-lg" onClick={(event) => event.stopPropagation()}><b className="mb-3 block text-slate-500">My Companies</b><div className="flex items-start justify-between border-b border-slate-100 pb-3"><span><strong className="block">Paytel Financial Services Pvt Ltd 22-23</strong><small className="text-slate-500">Synced a day ago</small></span><span className="text-green-600">✓</span></div><b className="my-3 block text-slate-500">New Companies</b><div className="flex items-center justify-between"><span><strong className="block">PayTel Financial Technologies Pvt. Ltd.</strong><small className="text-slate-500">(Delhi)</small></span><button type="button" className="rounded bg-slate-900 px-3 py-1 text-white">Add</button></div></div>}
      </div>
      <label className="header-search mx-auto flex h-9 w-[clamp(180px,28vw,320px)] items-center rounded-lg border border-slate-300 px-3 text-slate-400"><span className="mr-2 text-lg">⌕</span><input type="text" placeholder="Search vouchers, ledgers, items" className="w-full bg-transparent text-[11px] text-slate-800 outline-none placeholder:text-slate-400" /></label>
      <div className="ml-3 flex h-[60px] shrink-0 items-stretch"><button type="button" onClick={() => setShowEway(true)} className="flex w-[82px] items-center justify-center gap-2 border-0 border-r border-slate-200 bg-white text-[11px]"><span className="grid h-[18px] w-[18px] place-items-center rounded-full border border-red-400 text-red-500">!</span><span className="text-left leading-[13px]">Link<br />eWay</span></button><button type="button" className="flex w-[106px] items-center justify-center gap-2 border-0 border-r border-slate-200 bg-white text-[11px]"><span className="text-xl">▯</span><span className="text-left leading-[13px]">Mobile<br />Version</span></button><div className="relative"><button type="button" aria-label="Open profile menu" aria-expanded={showProfileMenu} onClick={() => setShowProfileMenu((current) => !current)} className="flex h-[60px] min-w-[75px] items-center justify-center gap-2 border-0 bg-white px-3 text-lg"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-sm">♙</span><span className="text-xs">⌄</span></button>{showProfileMenu && <div className="absolute right-2 top-[60px] z-30 w-44 rounded border border-slate-200 bg-white p-1 shadow-lg" role="menu">{profileItems.map((label) => <button type="button" role="menuitem" key={label} onClick={() => setShowProfileMenu(false)} className="block w-full rounded px-3 py-2 text-left text-xs hover:bg-slate-100">{label}</button>)}</div>}</div></div>
    </header>
    {showCompanyMenu && <button className="fixed inset-0 z-10 cursor-default bg-transparent" type="button" aria-label="Close company menu" onClick={() => setShowCompanyMenu(false)} />}
  </>
}

export default AppHeader
